/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubcategoriesRouteImport } from './routes/admin.subcategories'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPriceTrackingRouteImport } from './routes/admin.price-tracking'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMarketplacesRouteImport } from './routes/admin.marketplaces'
import { Route as AdminImportExportRouteImport } from './routes/admin.import-export'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesRoute = AdminSubcategoriesRouteImport.update({
  id: '/subcategories',
  path: '/subcategories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPriceTrackingRoute = AdminPriceTrackingRouteImport.update({
  id: '/price-tracking',
  path: '/price-tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplacesRoute = AdminMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportExportRoute = AdminImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/import-export': typeof AdminImportExportRoute
  '/admin/marketplaces': typeof AdminMarketplacesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/price-tracking': typeof AdminPriceTrackingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/users': typeof AdminUsersRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/import-export': typeof AdminImportExportRoute
  '/admin/marketplaces': typeof AdminMarketplacesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/price-tracking': typeof AdminPriceTrackingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/users': typeof AdminUsersRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/import-export': typeof AdminImportExportRoute
  '/admin/marketplaces': typeof AdminMarketplacesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/price-tracking': typeof AdminPriceTrackingRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/users': typeof AdminUsersRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/search'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/import-export'
    | '/admin/marketplaces'
    | '/admin/notifications'
    | '/admin/price-tracking'
    | '/admin/products'
    | '/admin/subcategories'
    | '/admin/users'
    | '/product/$id'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/search'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/import-export'
    | '/admin/marketplaces'
    | '/admin/notifications'
    | '/admin/price-tracking'
    | '/admin/products'
    | '/admin/subcategories'
    | '/admin/users'
    | '/product/$id'
    | '/admin'
    | '/admin/products/$id'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/search'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/import-export'
    | '/admin/marketplaces'
    | '/admin/notifications'
    | '/admin/price-tracking'
    | '/admin/products'
    | '/admin/subcategories'
    | '/admin/users'
    | '/product/$id'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories': {
      id: '/admin/subcategories'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/price-tracking': {
      id: '/admin/price-tracking'
      path: '/price-tracking'
      fullPath: '/admin/price-tracking'
      preLoaderRoute: typeof AdminPriceTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplaces': {
      id: '/admin/marketplaces'
      path: '/marketplaces'
      fullPath: '/admin/marketplaces'
      preLoaderRoute: typeof AdminMarketplacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import-export': {
      id: '/admin/import-export'
      path: '/import-export'
      fullPath: '/admin/import-export'
      preLoaderRoute: typeof AdminImportExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminImportExportRoute: typeof AdminImportExportRoute
  AdminMarketplacesRoute: typeof AdminMarketplacesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPriceTrackingRoute: typeof AdminPriceTrackingRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminSubcategoriesRoute: typeof AdminSubcategoriesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminImportExportRoute: AdminImportExportRoute,
  AdminMarketplacesRoute: AdminMarketplacesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPriceTrackingRoute: AdminPriceTrackingRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminSubcategoriesRoute: AdminSubcategoriesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
